insert into NHACUNGCAP(MANHA, TENNHA, DIACHI, SODT, MASOTHUE)
VALUES('NCC001',N'CTY TNHH TOÀN PHÁP','HAI CHAU',0511399988,568941)


insert into LOAIDICHVU(MALOAIDV, TENLOAIDV)
values('DP01',N'DỊCH VỤ XE TAXI')


INSERT INTO MUCPHI(MAMP, DONGIA, MOTA)
VALUES('MP01',10.000,N'ÁP DỤNG TỪ 1/2015')


INSERT INTO DONGXE(DONGXE, HANGXE, SOCHONGOI)
VALUES('HIACE','TOYOTA',16)

SELECT * FROM NHACUNGCAP
SELECT * FROM LOAIDICHVU
SELECT * FROM MUCPHI
SELECT * FROM DONGXE

